### ISSUE TITLE
ss_podcast shortcode issue

### ISSUE THREAD

**Issue by llahnoraa** [hlashbrooke/Seriously-Simple-Podcasting#100]
[Per your ss_podcast documentation](https://www.seriouslysimplepodcasting.com/documentation/ss_podcast/), `link_title="false"` still show link. I am not 100% sure if it's a bug or not... please advise.

**Comment by llahnoraa** [comment]
I just commented out this code on line 111 - 113 and the link no longer appeared. Exactly what I want.

`if ( true == $args['link_title'] ) {
$title = '<a href="' . esc_url( $post->url ) . '" title="' . esc_attr( $title ) . '">' . $title . '</a>';
}`

**Comment by hlashbrooke** [comment]
This shortcode is pretty much deprecated now and I would recommend that you use the new [`podcast_playlist` shortcode](https://www.seriouslysimplepodcasting.com/documentation/podcast_playlist/) instead if you would like to show a list of episodes on one page. I know it's not exactly the same, but the `ss_podcast` shortcode has never really worked all that well and I've been wanting to deprecate it for ages.
