### ISSUE TITLE
`ssp_feed_channel_link_tag` - is this active?

### ISSUE THREAD

**Issue by philoushka** [hlashbrooke/Seriously-Simple-Podcasting#122]
I love your plugin, and I'd like to adopt it to host my own set of multiple podcasts.

One thing I noticed - the RSS `<channel><link>` is the same for all podcast series that you define.

I see that you added a new variable that might be intended to solve my problem.

 `ssp_feed_channel_link_tag`

Can you confirm whether users are able to currently define per-podcast website URLs for the output `<channel><link>` ?

https://github.com/hlashbrooke/Seriously-Simple-Podcasting/blob/master/templates/feed-podcast.php#L274

**Comment by hlashbrooke** [comment]
Yes - this was done intentionally, as the home URL for all the series is (in most cases) the home page of the website. That is why I supplied the `ssp_feed_channel_link_tag` filter that includes the current series slug as an argument.

You could use it something like this if you wanted to get the series URL for series feeds, but still use the main site URL for the main feed:

```
add_filter( 'ssp_feed_channel_link_tag', 'philoushka_custom_feed_channel_link_tag', 10, 2 );
function philoushka_custom_feed_channel_link_tag ( $url = '', $series_slug = '' ) {
  if( $series_slug ) {
    $url = get_term_link( $series_slug, 'series' );
  }
  return $url;
}
```

You can paste the snippet into your theme's functions.php file or into a custom functionality plugin.

**Comment by philoushka** [comment]
Hi Hugh - I'm curious how/where I can specify the URL for the podcast series. Is there something I can modify?


![image](https://cloud.githubusercontent.com/assets/930731/18290040/c5f462b4-7436-11e6-8244-d6b7dadc80c3.png)


![image](https://cloud.githubusercontent.com/assets/930731/18290087/f269183a-7436-11e6-91b4-9e0911ab79fa.png)

**Comment by hlashbrooke** [comment]
GitHub is not the right place for support - these kinds of questions are better asked in the [plugin's support forum](https://wordpress.org/support/plugin/seriously-simple-podcasting).

While I'm here, however, I may as well answer. The URL slug is taken from the series slug that is auto-generated by WordPress when you create the series. You can go to **Podcast > Series** to edit the slugs if you like.
