### ISSUE TITLE
GUID Issue When Importing Feed

### ISSUE THREAD

**Issue by tracerx** [hlashbrooke/Seriously-Simple-Podcasting#125]
I am migrating to SSP from another system where my GUID was not a url. (e.g. e110a-missingthemouse.co). I figured out how to update the GUID's in Wordpress to match the current GUID's in my feed however, due to the esc_url filter on the_guid, my GUID's in the feed were being prepended with http:// . I added
`remove_filter('the_guid','esc_url');`
to feed-podcast.php which seems like it would still be ok since the_guid is wrapped in esc_html but I will admit that I don't spend a lot of time working in PHP or WordPress so I could also be completely offbase. Just thought I'd bring it up since it might make it easier for people transitioning to SSP.

**Comment by hlashbrooke** [comment]
The GUID generation is done by WordPress core itself, so the `esc_url` function is applied inside core and has nothing to do with this plugin.

I would suggest moving your `remove_filter('the_guid','esc_url');` call to a different location (either in your theme's `functions.php` file or in a custom functionality plugin as that would make it more certain of being triggered correctly.

That being said - as this is not a plugin problem, but rather an conflict between your existing data and the way WordPress core does things, I'm going to close this issue.
