### ISSUE TITLE
Feed Validity and FeedPress

### ISSUE THREAD

**Issue by gabhart** [hlashbrooke/Seriously-Simple-Podcasting#25]
I am attempting to use FeedPress to distribute my podcast, but I continue to get errors indicating that my feed does not validate.

Here's the W3C validator results:

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fequipyourmarriage.com%2F%3Ffeed%3Dpodcast

**Comment by hlashbrooke** [comment]
Please test this with the latest version of the plugin and let me know if you still have an issue.
