### ISSUE TITLE
Podcast download stats

### ISSUE THREAD

**Issue by hlashbrooke** [hlashbrooke/Seriously-Simple-Podcasting#39]
After having (finally) worked out how to reliably link to podcast episode downloads so they will work in all feed readers **and also be trackable via the `ssp_file_download` action hook**, I can now start adding stats tracking and analytics to the plugin.

This raises the question of what to track and how to track it. In this case the 'what' will inform the 'how', so I need to know what kind of analytics people are wanting/needing. If any users who are needing stats tracking could indicate their needs here then I'll be able to compile a list of the tracking features to be added. I will keep the list updated in this description.

**The current list of potential features is as follows:**

- [x] Total number of downloads per episode
- [x] Number of downloads for a given date range
- [x] Number of downloads per episode for a given date range
- [x] Number of downloads per series for a given date range
- [x] Referrer (browser, iTunes, Stitcher, etc.)
- [x] Total number of actual subscribers (probably counted by IP address)

*Please make suggestions below so I can update the list and make some informed development decisions.*

**Comment by garethallison** [comment]
Perhaps a very bare-boned form of analytics. eg. which country a listener is from? Perhaps a percentage indicator of how long they listend to the podcast itself?

**Comment by anotherfluke** [comment]
This isn't totally related to stats, but my main reason for wanting stats is to have the ability to gate downloads by either download count or data used.  So if you can tie data used to download count, that would be a helpful metric.

**Comment by hlashbrooke** [comment]
@anotherfluke Interesting idea. We already have the file size of the audio file and if we just multiply that by the number of downloads then I guess we'll get the total data usage. The problem then is that some people will only listen to part of the file and I'm not sure if we'll be able to track that kind of thing, but I'm going to see what's possible on that front. Thanks for the input :)

**Comment by jamesbullbrook** [comment]
All of the above will be incredibly useful. I'd also be curious if there was way to quantify if someone is a subscriber vs one-time downloader.

**Comment by hlashbrooke** [comment]
Thanks @jamesbullbrook - I'm not sure if we'll be able to track subscribers exactly, but if we count the number of different IP addresses being used to download files then that should give us a somewhat accurate count of the amount of different people who are subscribed. It won't be exact, but it should be close.

**Comment by spearsmarketing** [comment]
All of the above seem like good stats to track. I have noticed that since the most recent update that the "download file" link isn't working, it redirects to the homepage. Here's a link if you want to take a look: http://wellnessmama.com/podcast/wm026-fasting-for-women-music-therapy/

**Comment by hlashbrooke** [comment]
@spearsmarketing This thread is specifically for working out the best stats tracking options. Please post your issue on the [http://wordpress.org/support/plugin/seriously-simple-podcasting](support forum) instead and we can work things out there.

**Comment by anotherfluke** [comment]
Hi, @hlashbrooke I am really enjoying all of the regular tweaks and fixes you do for this plugin, and am very thankful that you continue to improve SSP!  I'm curious though if you've made any progress on download tracking, or when we might see it in an upcoming update?

Thanks again!

**Comment by nickd32** [comment]
Hi @hlashbrooke, we're loving the plugin -- what a breath of fresh air after using other WP podcasting plugins for several years.  re: tracking, we're looking for both download stats and subscriber stats.

I found this article, where a guy offers a PHP script that tracks stats using Google Analytics Events:
http://www.chrisvanpatten.com/track-podcast-downloads-google-analytics-events-free-php-script

Perhaps that could help?  They're getting the subscriber stats from FeedPress... I'm hopefully we can get subscription numbers without having to use a 3rd-party service.

**Comment by whyisjake** [comment]
For those that are interested in stats in the short term, I wrote [this plugin](https://wordpress.org/plugins/add-podtrac-to-seriously-simple-podcasting/ ) that goes hand in hand with SSP. It uses Podtrac for download/subscriber stats.

**Comment by hlashbrooke** [comment]
I started working on a stats add-on a little while ago and it is here in its incomplete form: https://github.com/hlashbrooke/SSP-Stats - feel free to grab that code and use it, but remember that it's thoroughly incomplete still.

**Comment by heyjones** [comment]
Got it installed, love the podcast plugin! Was working on writing my own Google Analytics integration before I found the link to the alpha. Got it installed but I don't see any additional links in wp-admin.

**Comment by hlashbrooke** [comment]
After doing a bunch of research into the best options here, I'll be building this by capturing the listener info in a custom database table, then displaying the info on the episode edit screen as well as a new Podcast Stats page. The display on the episode edit screen will be basic numbers, but the stats page will use visual graphs that will be generated with the [Google Charts API](https://google-developers.appspot.com/chart/).

Version 1 will track the following data:
- Listener IP address
- Date
- Referrer

The referrer could be something like iTunes or Stitcher, or otherwise it would be a direct download, played via the audio player, or played in a new window. If I can work out ways of tracking other referrers then I will do so.

In version 1, the stats page will show the following information:
- Line graph of daily download counts
- Pie chart of referrers

All charts will have date selection options as well as the ability to be displayed per episode, per series, or for all episodes.

I think that should be robust enough for version 1 - I can add more features in future releases based on customer feedback and requests.

If you have any immediate feedback on this please just comment below so I don't go on the completely wrong track :)

**Comment by anotherfluke** [comment]
That is amazing, thanks Hugh!  Can't wait to try this out :)

~N

**Comment by hlashbrooke** [comment]
v1 of Seriously Simple Stats is now live and available on the WordPress plugin repo: https://wordpress.org/plugins/seriously-simple-stats/ :)

I'm going to close this thread now, so if you have any queries about the add-on either post on the add-on's [support forum](https://wordpress.org/support/plugin/seriously-simple-stats) or in [the GitHub repo](https://github.com/hlashbrooke/Seriously-Simple-Stats).

Of course, [a few reviews](https://wordpress.org/support/view/plugin-reviews/seriously-simple-stats?rate=5#postform) of the add-on would be greatly appreciated and would go a long way towards supporting continued development.
