### ISSUE TITLE
Podcast CPT added to "Uncategorized" Post category?

### ISSUE THREAD

**Issue by Fred-FLQ** [hlashbrooke/Seriously-Simple-Podcasting#40]
Hi Hugh!

It's Fred again. Everything went smoothly during the transition, thanks for your advices on the support forum. Sorry to put a message here but I thought it was more of an issue than a support question (I already solved it for my website).

I'm only using the Podcast CPT but I got all the podcasts showing up in my Blog Page. I of course didn't check the "Include podcast in main blog" option + my blog page is actually set up to only show Posts from certain Categories. One of them was the "Uncategorized" default WP one. After removing it from my set up, all Podcast posts disappeared.

Thus it feels like, even though there is no Category for the Podcast CPT, they are being assigned the "Uncategorized" Post category.

Did you ever have any feedback about that ?

Fred

---
WP 4.1.1
SSP 1.8.11

**Comment by hlashbrooke** [comment]
Hi Fred,

Thanks for this - I haven't noticed this before, but I'll check it out on my side.

In the mean time could you please test that this isn't a plugin/theme conflict on your site by disabling all of your other plugins and reverting to one one of the default WordPress themes (Twenty Twelve, etc.). That will help rule out conflicts and narrow down the problem a bit.

Thanks!

**Comment by Fred-FLQ** [comment]
Sure, I'll do some extra testing on my local install and keep you updated. ;)

**Comment by hlashbrooke** [comment]
@Fred-FLQ I've done some testing here and I'm unable to replicate this issue, so I'm inclined to think that it's an issue on your side. My best guess would be that you have a plugin that is forcing all post types  to use the blog categories or something along those lines, but I can't be sure.

**Comment by Fred-FLQ** [comment]
@hlashbrooke Ok! I just updated my local install: if I find something while looking into it I'll keep you updated. :smile: 
Thanks again for this great plugin!
