### ISSUE TITLE
Decouple or allow hooks of included custom post type?

### ISSUE THREAD

**Issue by dryanmedia** [hlashbrooke/Seriously-Simple-Podcasting#44]
Terrific plugin! Great work!

It'd be awesome if the included Custom Post Type could be changed (without forking) so that the URL rewrite and labels could be customized with ease. 

It's awesome that the podcasts can be applied to other post types, but then you have the UX confusion of things like "Podcasts" vs "Episodes" or "Podcasts" vs "Sermons."

I'd be happy to beer you or caffeine you!

**Comment by hlashbrooke** [comment]
There's a filter for that :)

I actually did that recently for a site I built where I renamed 'Podcast' to 'Talks' - this is the code I used:

```php
add_filter( 'ssp_archive_slug', 'mod_podcast_archive_slug', 10, 1 );
function mod_podcast_archive_slug ( $slug ) {
	return 'talks';
}

add_filter( 'ssp_register_post_type_args', 'mod_podcast_custom_args', 10, 1 );
function mod_podcast_custom_args ( $args ) {

	$args['labels'] = array(
		'name' => _x( 'Talks', 'post type general name' , 'ss-podcasting' ),
		'singular_name' => _x( 'Talk', 'post type singular name' , 'ss-podcasting' ),
		'add_new' => _x( 'Add New', 'podcast' , 'ss-podcasting' ),
		'add_new_item' => sprintf( __( 'Add New %s' , 'ss-podcasting' ), __( 'Talk' , 'ss-podcasting' ) ),
		'edit_item' => sprintf( __( 'Edit %s' , 'ss-podcasting' ), __( 'Talk' , 'ss-podcasting' ) ),
		'new_item' => sprintf( __( 'New %s' , 'ss-podcasting' ), __( 'Talk' , 'ss-podcasting' ) ),
		'all_items' => sprintf( __( 'All %s' , 'ss-podcasting' ), __( 'Talks' , 'ss-podcasting' ) ),
		'view_item' => sprintf( __( 'View %s' , 'ss-podcasting' ), __( 'Talk' , 'ss-podcasting' ) ),
		'search_items' => sprintf( __( 'Search %a' , 'ss-podcasting' ), __( 'Talks' , 'ss-podcasting' ) ),
		'not_found' =>  sprintf( __( 'No %s Found' , 'ss-podcasting' ), __( 'Talks' , 'ss-podcasting' ) ),
		'not_found_in_trash' => sprintf( __( 'No %s Found In Trash' , 'ss-podcasting' ), __( 'Talks' , 'ss-podcasting' ) ),
		'parent_item_colon' => '',
		'menu_name' => __( 'Talks' , 'ss-podcasting' ),
	);

	return $args;
}
```

That snippet does two things - the first bit changes the URL structure to be `talks` instead of `podcast` (after adding it you will need to re-save your site's permalinks) and the second bit changes the text labels to read as `Talks` and `Talk` everywhere in the dashboard.

Adding all of that to your theme's functions.php file will sort it all out for you :)

**Comment by dryanmedia** [comment]
Terrific, thanks @hlashbrooke!
