### ISSUE TITLE
Allow episode to be embedded on external site

### ISSUE THREAD

**Issue by hlashbrooke** [hlashbrooke/Seriously-Simple-Podcasting#47]
This would most likely work as an `iframe` tag, but it would essentially be a way of displaying your episodes on any other website by pasting in a snippet of HTML.

**Comment by whyisjake** [comment]
Would be cool to use the JSON API to do something like this...

**Comment by hlashbrooke** [comment]
I agree, which is why I'm waiting for the API to be included in core before thinking about this further :)

**Comment by hlashbrooke** [comment]
This might actually be a better option: https://make.wordpress.org/core/2015/09/02/oembed-feature-plugin-update/ - with any luck that will be in core soon and it will presumably be easy to filter so we can just add the podcast player & meta to the output.

**Comment by whyisjake** [comment]
Hah, was just going to add a link to the oEmbed plugin.

**Comment by hlashbrooke** [comment]
It looks oEmbed is going to be included in WordPress 4.4 for definite, so will hold off on this feature until then. And, once it is available in WordPress core, we can simply add filters for the podcast data inside SSP itself instead of building this feature as a separate extension.

**Comment by hlashbrooke** [comment]
oEmbed has been officially merged into WordPress core: https://core.trac.wordpress.org/changeset/34903, so I will start working on this feature and maybe even have it ready for when 4.4 drops (but no promises) :)

**Comment by whyisjake** [comment]
This is like ridiculously easy now...

![image](https://cloud.githubusercontent.com/assets/848187/10407683/142eb442-6ea3-11e5-8d41-d95b014c75c9.png)

**Comment by hlashbrooke** [comment]
Closed via #71

**Comment by rob** [comment]
Sorry for bring up an old thread, but is there a way to embed an episode using an `<iframe>` tag?

We're trying to embed an episode on a third-party website that doesn't support oEmbed, so our only option is to use an `<iframe>`. I know Blubrry's plugin supports this, but I'd like to stay away from that if possible.
