### ISSUE TITLE
Need a way to redirect individual feeds, not just the main one.

### ISSUE THREAD

**Issue by whyisjake** [hlashbrooke/Seriously-Simple-Podcasting#54]
For a site that has multiple podcasts, you may need to add a redirect for an individual show. I suggest moving the the redirection page into the feed details page.

**Comment by hlashbrooke** [comment]
That's a good point - just got a support request asking the same thing: https://wordpress.org/support/topic/redirect-single-series - will look into that as an option in the next release.

**Comment by whyisjake** [comment]
Created a PR with this feature in mind. :) https://github.com/hlashbrooke/Seriously-Simple-Podcasting/pull/56

**Comment by hlashbrooke** [comment]
Merged and will be added in v1.11
