### ISSUE TITLE
Add caching to ssp_episodes()

### ISSUE THREAD

**Issue by hlashbrooke** [hlashbrooke/Seriously-Simple-Podcasting#59]
Need to improve performance inside `ssp_episodes()` as this function is called a lot. Transients would probably be the best bet, but they would need to be cleared when a new episode is added to prevent inconsistencies.

**Comment by hlashbrooke** [comment]
@whyisjake You had some ideas here, so let me know what you were thinking.

**Comment by whyisjake** [comment]
Started a PR here: https://github.com/hlashbrooke/Seriously-Simple-Podcasting/pull/63

Those unbound queries (`posts_per_page => -1`) can be quite worrisome on sites with a lot of podcasts.

**Comment by hlashbrooke** [comment]
Fixed in v1.11 :)
