### ISSUE TITLE
Move series-specific feed details to the taxonomy term edit screen (requires WordPress 4.4+)

### ISSUE THREAD

**Issue by hlashbrooke** [hlashbrooke/Seriously-Simple-Podcasting#68]
Currently, you need to have the `manage_options` capability (which more often than not means becoming a site administrator) in order to edit any of the podcast settings, which includes the feed details. This causes problems when a site has an author or editor managing the content, but not the options. In that case, they cannot edit the feed details at all.

With taxonomy term meta data landing in WordPress 4.4, it would make sense to move the series-specific feed details to the taxonomy term edit screen. This would allow authors/editors to manage that content without having to be given the `manage_options` capability.

The global feed details could remain where they are as I would consider those as more general settings instead of content management like it is with the series-specific feed details. Once WordPress 4.4 drops, it will be worth looking into this as a possible enhancement.

**Comment by hlashbrooke** [comment]
Something to bear in mind is that if this were to happen, it would be unrealistic to maintain the current system alongside the new one. That would mean breaking compatibility with any WordPress versions prior to 4.4. That might mean that its worth waiting until the 4.5 release before implementing this enhancement.

**Comment by whyisjake** [comment]
On the other hand, it might make more sense to keep all options in the same place. I have considered removing the series page so that people don't poke around in there.

**Comment by hlashbrooke** [comment]
Perhaps a better solution is to leave it all as it is, but instead set a custom capability (something like `manage_podcast`) for managing the podcast settings, which can then be assigned to any user or role as needed (but would default to site admins only).

**Comment by whyisjake** [comment]
:+1: :+1: :+1:

**Comment by hlashbrooke** [comment]
Closed via #70
