### ISSUE TITLE
Add Video Podcasting

### ISSUE THREAD

**Issue by readej** [hlashbrooke/Seriously-Simple-Podcasting#84]
Could you add video podcasting to this plugin as well?

In this [support thread](https://wordpress.org/support/topic/video-podcasting-1?replies=4) for the plugin, Hugh Lashbrooke says that he is "looking into the best way to effectively provide video podcasting capabilities."

Has any work been done on this yet?

I have PHP development experience and I may be able to help with the development of this feature.

**Comment by whyisjake** [comment]
So, adding support in the player?

**Comment by readej** [comment]
Yes, generally.

It would be nice if you could include an mp3, mp4, or both when creating the podcast episode. Then, when viewing the episode, it would show the video player(if set), and/or the audio player(if set). There would be 2 download links if both formats were set. 1 for video download, and 1 for audio-only download.

If this is too difficult, I would be happy with just a "Podcast File:" metabox that would accept either mp3 OR mp4.

Changing the word "Audio" to "Podcast" throughout the admin screens would also be necessary in both options. For example, "Duration of audio file for display" would become "Duration of podcast file for display".

**Comment by readej** [comment]
Actually, now that I've looked into the code a little more, I think I might have found a solution (built-in to the plugin) to change the audio player to a video player. I found [this](http://www.seriouslysimplepodcasting.com/documentation/filter-reference/#ssp-audio-player).

So I added the following code to my functions.php (should be moved to a custom plugin in the future):
```
function replace_ssp_audio_player_with_video_player( $player, $src ) {
	$player = wp_video_shortcode( array( 'src' => $src, 'preload' => 'none' ) );
	return $player;
}
add_filter( 'ssp_audio_player', 'replace_ssp_audio_player_with_video_player', 10, 2 );
```

**Comment by whyisjake** [comment]
One option could be to check the mime-type of the file, and the choose which player to use based on that.

**Comment by readej** [comment]
Where would be the best place to check the mime-type?

**Comment by whyisjake** [comment]
There is a method in the class called `get_attachment_mimetype()` that you could pass the URL into. 

https://github.com/hlashbrooke/Seriously-Simple-Podcasting/blob/master/includes/class-ssp-frontend.php#L613-L643

**Comment by readej** [comment]
The function `get_attachment_mimetype()` does not exist when I call it in a function in my custom plugin.

**Comment by whyisjake** [comment]
There is a global that is set in the plugin to give you access.

````php
<?php

function replace_ssp_audio_player_with_video_player( $player, $src ) {
	global $ss_podcasting;
	$mime = $ss_podcasting->get_attachment_mimetype( $src );

	if ( $mime == 'mpeg/4blahblagasdf' ) {
		$player = wp_video_shortcode( array( 'src' => $src, 'preload' => 'none' ) );
	} else {
		$player = wp_audio_shortcode( array( 'src' => $src, 'preload' => 'none' ) );
	}
	return $player;
}
add_filter( 'ssp_audio_player', 'replace_ssp_audio_player_with_video_player', 10, 2 );

**Comment by whyisjake** [comment]
To be clear here tho, I would do a bunch of testing around that, mime type and WordPress are notoriously difficult.

**Comment by readej** [comment]
oh yeah... doh....

But `$mime = $ss_podcasting->get_attachment_mimetype( $src );` returns false.

Maybe `$src` is not the right thing to pass `get_attachment_mimetype` ?

**Comment by whyisjake** [comment]
Yeah, at the core, [get_mime_type()](https://codex.wordpress.org/Function_Reference/get_post_mime_type) returns false if it doesn't know the mime of the media. If it gets a false, you could do some string matching on the extension of the URL, based on know types. (ie, if .mp3 then audio, if .mp4, then video...)

**Comment by readej** [comment]
I'm done for the day... this is what I ended up with:
```
function replace_ssp_audio_player_with_video_player( $player, $src ) {
	if ( strpos($src,'mp4') !== false ) {
		$player = wp_video_shortcode( array( 'src' => $src, 'preload' => 'none' ) );
		return $player;
	}
	return $player;
}
add_filter( 'ssp_audio_player', 'replace_ssp_audio_player_with_video_player', 10, 2 );
```

**Comment by whyisjake** [comment]
![Amazing](http://www.reactiongifs.com/r/2011/05/amazing.gif)

**Comment by hlashbrooke** [comment]
I commented on your support thread about this already, but just to say that video podcasting is about more than substituting the media player - it would also mean making changes to the admin UI as well as the RSS feed structure per episode. That needs research and work to be put in that I just haven't had the time to put in yet. I will get to it, but in the mean time - pull requests are always welcome :)

**Comment by readej** [comment]
Yes, I realize it is more than just changing the media player. I was thinking it might be better to make it as another plugin "Seriously Simple Video Podcasting".

I'm very busy re-building a Drupal website into a WordPress website right now. Video podcasting was a requirement and it was this plugin's simplicity and well written code that made me chose it over Blubrry PowerPress, which is, in my opinion, bloated.

When I get more time, I will try to do some research on the RSS feed structure and what changes to the admin UI are needed. But making our videos into "true podcast" that people can subscribe to and view on external sites is going to be a future goal. Right now, we just want to have a way to organize podcasts into series and have people view them on our website. Maybe I should have just built my own custom post type and a custom taxonomy for the series? This seemed simpler to meet the requirement for now.

**Comment by hlashbrooke** [comment]
I've had a look into the RSS structure today and it actually looks like video podcasts have exactly the same structure - the only change is that the MIME type is different, but that would happen on the fly anyway. So that takes care of that side of things :)

That means the only thing that really needs to be done for this is updating the admin UI to indicate that either video or audio are supported and allow the uploader to indicate on each episode which type it is. That way we can easily show the video player instead of the audio player on the frontend and the RSS feed would actually take care of itself.

So this won't be as hard as I thought - just give me some time to work on the admin UI, as a simple UX on that front is super important to me and I want it to be just right.

**Comment by readej** [comment]
Ok sounds good!

![a-plan-comes-together](https://cloud.githubusercontent.com/assets/10283905/12357837/343a8fbe-bb78-11e5-8f28-abe85d4edcd3.jpg)

**Comment by hlashbrooke** [comment]
@readej: I've added video support to the plugin and it is available in the master branch of this repo. Could you test it out when you get a chance? I'd like to release this ASAP if it's all working correctly.

@whyisjake: Your eyes on this would also be valuable :)

The flow is that there is a new option on the episode edit screen to select either audio or video - this defaults to audio, so if you don't use video you can just ignore the option. The audio default also means that older episodes will still function as audio episodes, so there won't be any backwards compatibility issues.

On the frontend, the audio player is replaced with the video player if video is selected as the episode type. The video player will then use the episode's featured image as the video 'poster' (i.e. the image that is displayed as a placeholder in the player until you hit the play button).

The feed will work automatically as I mentioned previously - the only difference now is that the default MIME type is `video/mp4` for video episodes instead of the usual `audio/mpeg` that audio episodes have as a default. This default only comes in to play if there is no way for WordPress to detect the file MIME type programmatically, so it is more of a fallback to prevent broken feeds than anything else.

**Comment by whyisjake** [comment]
Doesn't have to be part of this release, but it would be nice to offer
multi upload support. That way you can embed ogg, MP3, MP4, and pdf. iTunes
has support for video, pdf, and audio.

**Comment by readej** [comment]
@whyisjake That is more like what I was thinking from the beginning. But like you said, it doesn't have to be part of this release.

@hlashbrooke I installed the plugin on my development site and it seems to be working perfectly. I looked through the changes you made and they all look good to me.

**Comment by whyisjake** [comment]
I'm traveling today, and at a funeral tomorrow so won't be able to do any
testing right now. Sorry.

**Comment by hlashbrooke** [comment]
No worries @whyisjake - I'm confident this is working soundly.

I also like the idea of allowing multiple media types per episode, but I'm thinking that might be better as an extension - it's something that I don't think will be used by the majority of people, but it will have a significant impact on the UI and I wouldn't want to clutter the UI with extra fields that most people won't use.

Either way, that is definitely something worth looking into, so I'll open a separate issue for it.

Closing this issue as video support is now in master branch, so we're all sorted here.

**Comment by readej** [comment]
I'm having an issue putting a https://vimeo.com link in the "Podcast file" location. Because vimeo links are of the format https://vimeo.com/123456789 the ext defaults to .mp3

The extension be based on what the user selected as the Episode type. mp4 for video mp3 for audio.

**Comment by whyisjake** [comment]
I'm not sure that a Vimeo video would be the appropriate thing for an RSS enclosure @readej. From the spec: 

<enclosure> sub-element of <item>
<enclosure> is an optional sub-element of <item>.
It has three required attributes. url says where the enclosure is located, length says how big it is in bytes, and type says what its type is, a standard MIME type.
The url must be an http url.

With Vimeo, it is a link, not a URL to something that can be enclosed in the feed, like an MP3, or video file. A podcast reader would read the mime type, and then decide how to play that resource, something they couldn't do with a Vimeo url. 

![screen shot 2016-02-09 at 2 22 26 pm](https://cloud.githubusercontent.com/assets/848187/12932692/c52d780a-cf38-11e5-8555-10f2458826c7.png)

I think that if you are looking for a templating solution, a shortcode would be a better option, or a custom field that is external to SSP. For WIRED, we have a custom field in SSP where we put a SoundCloud URL that we show on the front-end via custom shortcode.

![screen shot 2016-02-09 at 2 22 39 pm](https://cloud.githubusercontent.com/assets/848187/12932683/b85109a8-cf38-11e5-9a47-e9fe0d758c7d.png)

**Comment by readej** [comment]
Yeah, I thought about that type of solution... I might be doing something like that.

I was just seeing if you had anyone bring this vimeo issue to your attention before. If there was a solution buried within vimeo. Like a .mp4 link in vimeo I was missing. I don't believe there is one.

The issue is that we have a lot of vimeo videos and we would like to have vimeo host those videos rather than host them ourselves. There would be no actual file to upload on our site, which kinda defeats the purpose of this plugin, or at least some of the nice features of the plugin.

**Comment by whyisjake** [comment]
If you dig into the oEmbed response, you can find some vars that have links to mp4 files. In the case of [this video](https://player.vimeo.com/video/154356639), you there is a [video here](https://skyfiregcs-a.akamaihd.net/exp=1455066705~acl=%2A%2F476866978.mp4%2A~hmac=da4f2c7de8f3bedb3f99b167265afc67d593340aa4c445a70bec2b47af5e9d5b/2tierchgci/vimeo-prod-skyfire-std-us/01/871/6/154356639/476866978.mp4).

**Comment by readej** [comment]
Ok I will take a look later. Thank you.

**Comment by hlashbrooke** [comment]
If you don't include an actual video file (whether it is hosted on your server or another one) then there's no way that SSP (or any other podcasting plugin) can build an RSS feed for you that includes the video. The `enclosure` tag requires a direct media file to be provided in the`url` parameter - there's no way around that as that is an RSS standard and not anything that we can change. If you are including a standard Vimeo URL then it will never work in any podcast feed no matter what plugin you use.

If you host your videos on Vimeo, you will need to see if Vimeo can provide a URL directly to your video files. The other option is as @whyisjake suggested - embed your Vimeo video in the post content and include the raw video file in the feed.
