### ISSUE TITLE
Podtrac links are http only

### ISSUE THREAD

**Issue by bottiger** [hlashbrooke/Seriously-Simple-Podcasting#94]
Hello, very nice plugin.

I am working on migrating my site to SSL/TLS but the links generated by Serious Simple Podcasting to Podtrac are unfortunately HTTP only - giving me a mixed content warning. 

I am not talking about the custom Podtrac feed, but their episode redirect service with links like this:

     http://www.podtrac.com/pts/redirect.mp3/.....

They do support SSL/TLS so there so no reason for the links to be http.

Thanks

**Comment by hlashbrooke** [comment]
Are you referring to the Podtrac integration plugin? https://wordpress.org/plugins/add-podtrac-to-seriously-simple-podcasting/

If so, then @whyisjake will be able to answer your questions there as he is the one behind that add-on.

**Comment by simison** [comment]
This https://github.com/whyisjake/Podtrac-with-Seriously-Simple-Podcasting

**Comment by bottiger** [comment]
@hlashbrooke I think I am. Sorry about that

**Comment by simison** [comment]
(ping @whyisjake )

**Comment by whyisjake** [comment]
That's an easy update. I'll open a new issue.
